name: Create Release
on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: 'Git Tag'
        required: true
        type: string
env:
  UNITY_EMAIL: gilberto.alexsantos@gmail.com
jobs:
  generatePackage:
    name: Generate Unity Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.gitTag}}
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Ubuntu
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
          UNITY_EMAIL: ${{env.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}
        with:
          allowDirtyBuild: true
          targetPlatform: Android
          buildMethod: Builder.ExportPackage
          customParameters: -output_path /github/workspace/Builds/bluengine.unitypackage
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: Builds/bluengine.unitypackage
  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    needs: generatePackage
    env:
      PACKAGE_PATH: ${{format('{0}/Builds/bluengine.unitypackage', github.workspace)}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{inputs.gitTag}}
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: Builds
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{env.PACKAGE_PATH}}"
          tag: "${{inputs.gitTag}}"
          allowUpdates: true
      - name: Cleanup artifact
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build