name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: "Release type"
        required: true
        options: 
        - patch
        - minor
        - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Execute nuke release'
        run: ./build.sh release
        env:
          release-type: ${{ github.event.inputs.release-type }}
