name: Run Unity Tests
on: push
env:
  UNITY_EMAIL: gilberto.alexsantos@gmail.com
jobs:
  runUnityTest:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-blutoolbox-Android
          restore-keys: |
            Library-blutoolbox-
            Library-
      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          githubToken: ${{secrets.GITHUB_TOKEN}}