name: Run Unity Tests
on: push
env:
  UNITY_EMAIL: gilberto.alexsantos@gmail.com
jobs:
  runUnityTest:
    name: Run Unity Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-Ubuntu-Tests
          restore-keys: Library-
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{secrets.UNITY_LICENSE}}
          UNITY_EMAIL: ${{env.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{secrets.UNITY_PASSWORD}}
        with:
          githubToken: ${{secrets.GITHUB_TOKEN}}